/*

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

*/

#include <iostream>

int main(int argc, char* argv[]) {
	long int sum = 0;
	long int tmp;
	long int fib1 = 1;
	long int fib2 = 2;
	
	while (fib2 < 4000000) {
		if (fib2%2 == 0) {
			sum += fib2;
		}
		
		//get next fib
		tmp = fib2;
		fib2 = fib1 + fib2;
		fib1 = tmp;
	}
	
	std::cout << sum << std::endl;
}